### ISSUE TITLE
Slow Seq2EditDataset creation

### ISSUE THREAD

**Issue by helloeve** [cofe-ai/fast-gector#2]
Thank you for offering this AllenNLP-free version of gector. I was trying to play with it but realized the Seq2EditDataset can be quite slow as ~8it/s, which makes it impossible to process original dataset use by the paper (9M for pretrain). I wonder if this is normal, or I may miss something important to accelerate it?

**Comment by Jason3900** [comment]
I've just updated the tokenization scripts. Please pull the latest one and try again, thanks~
