### ISSUE TITLE
Reproduced results

### ISSUE THREAD

**Issue by Chunngai** [cofe-ai/fast-gector#3]
Hello. What are your reproduced results on the test sets?

**Comment by Jason3900** [comment]
I've tested stageII's performance, which is basically the same as reported in GECTOR's paper. Results from others also indicate that my implementation can achieve the similar performance.

**Comment by Chunngai** [comment]
OK.

Available parameters in this repo and the original gector repo are not completely the same. Do you plan to list parameters for each stage in the future?

**Comment by Jason3900** [comment]
Of course, but it may take some time since I decide to update the code and run the experiments again.

**Comment by Chunngai** [comment]
Good news! Looking forward to your update

**Comment by damien2012eng** [comment]
Good news! Looking forward to your update

**Comment by damien2012eng** [comment]
Hi Jason. I don't mean to rush you, just wondering any news regarding the update? Thanks!

**Comment by Jason3900** [comment]
> 
Hey, I've update training codes but for experiments it may take some time to proceed.
