### ISSUE TITLE
Result for another language

### ISSUE THREAD

**Issue by saramoeini20** [cofe-ai/fast-gector#7]
Hi,
I wanted to use this method for another language and i wanted to make the dataset myself.
Can i use it or this method and model has good result only for rich language and large dataset? I would be thankful if you answer me.

**Comment by Jason3900** [comment]
It may work for a language if you have pretrained models and thousands of training instances. But I've not tested yet. BTW, you can make some synthetic data for training stage I.

**Comment by saramoeini20** [comment]
How can i create synthetic data? I mean raw data that then i can use it for creating parallel data?

**Comment by Jason3900** [comment]
One way to do this is to use wiki edit history to get parallel edits.
