### ISSUE TITLE
Error in inference 

### ISSUE THREAD

**Issue by gagan3012** [cofe-ai/fast-gector#8]
0it [00:00, ?it/s]/home/coulombc/wheels_builder/tmp.17380/python-3.10/torch/aten/src/ATen/native/cuda/Indexing.cu:1141: indexSelectLargeIndex: block: [0,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/home/coulombc/wheels_builder/tmp.17380/python-3.10/torch/aten/src/ATen/native/cuda/Indexing.cu:1141: indexSelectLargeIndex: block: [0,0,0], thread: [1,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from c10_cuda_check_implementation at /home/coulombc/wheels_builder/tmp.17380/python-3.10/torch/c10/cuda/CUDAException.cpp:31 (most recent call first):

**Comment by Jason3900** [comment]
It's probably because the labels are out of bounds. Could you please provide more details in your experiment setting?

**Comment by Jason3900** [comment]
Hey, I've update inference codes. You can try it again.
