### ISSUE TITLE
What dataset?

### ISSUE THREAD

**Issue by akesh1235** [cofe-ai/fast-gector#9]
Hello sir,
i was wondering how fast-gector is capturing context of long sentences when it is only trained on some english tokens/words.

**Comment by Jason3900** [comment]
Hey, GECToR is a seq2edit model which mainly captures the edits from source to target instead of words/tokens. The long dependencies of error editing may require more iterations for a single instance. In the paper, the author indicates that there's a trade-off between speed and correction.

**Comment by akesh1235** [comment]
@Jason3900 
Thanks for replying,
What do you mean by More iterations for single instance?

You mean running more number of epochs while training??

**Comment by Jason3900** [comment]
What I mean is that GECToR uses iterative editing strategy in inference mode which modifies a sentence step by step. If an error requires long dependencies to find out, you can set more iteration number in order to capture it.
